name: Build the pppwn_live iso images

on:
  push:
    branches:
      - main

jobs:
  build_iso:
    name: Build and Cross-Compile ISO Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, aarch64]

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Alpine Linux based on architecture
      - name: Setup Alpine Linux ${{ matrix.architecture }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.architecture }}
          branch: edge
          packages: |
            alpine-sdk
            alpine-conf
            xorriso
            squashfs-tools
            grub
            grub-efi
            doas
            alpine-base
            busybox
            openrc
            bash
            agetty
            wget
            mtools
            dosfstools
          shell-name: alpine-${{ matrix.architecture }}.sh

      # Download and prepare PPPwn binary and assets
      - name: Prepare PPPwn Binaries for ${{ matrix.architecture }}
        shell: alpine-${{ matrix.architecture }}.sh --root {0}
        run: |
          [ -d /tmp/pppwntargz ] && rm -rf /tmp/pppwntargz
          mkdir -p /tmp/pppwntargz
          cd /tmp/pppwntargz
          wget https://github.com/xfangfang/PPPwn_cpp/releases/latest/download/${{ matrix.architecture }}-linux-musl.zip
          unzip -p ${{ matrix.architecture }}-linux-musl.zip | tar -xzOf - pppwn > pppwn && rm ${{ matrix.architecture }}-linux-musl.zip
          wget https://github.com/B-Dem/PPPwnUI/raw/main/PPPwn/goldhen/1100/stage1.bin
          wget https://github.com/B-Dem/PPPwnUI/raw/main/PPPwn/goldhen/1100/stage2.bin
          cd /tmp
          tar -czf pppwn-${{ matrix.architecture }}.tar.gz pppwntargz/*

      # Install required packages and prepare environment
      - name: Install Required Packages for ${{ matrix.architecture }}
        shell: alpine-${{ matrix.architecture }}.sh --root {0}
        run: |
          find /tmp -name "pppwn-${{ matrix.architecture }}.tar.gz" -exec cp {} aports/scripts/pppwn.tar.gz \;
          echo "permit nopass root" | tee -a /etc/doas.conf
          abuild-keygen -i -a -n -q
          apk update
          mkdir -p ~/tmp ~/work/iso/${{ matrix.architecture }}
          export TMPDIR=~/tmp
          cp -rf custom/* aports/scripts/
          chmod +x aports/scripts/*
          # WAR: Fix missing '/lib/libalpine.sh'
          ln -s /usr/lib/libalpine.sh /lib/libalpine.sh

      # Build ISO for specific architecture
      - name: Build ISO for ${{ matrix.architecture }}
        shell: alpine-${{ matrix.architecture }}.sh --root {0}
        run: |
          echo "Building ISO for ${{ matrix.architecture }}..."
          find /tmp -name "pppwn-${{ matrix.architecture }}.tar.gz" -exec cp -rf {} aports/scripts/pppwn.tar.gz \;
          sh aports/scripts/mkimage.sh --tag edge --outdir ~/work/iso/${{ matrix.architecture }} --arch ${{ matrix.architecture }} --repository https://dl-cdn.alpinelinux.org/alpine/edge/main --profile pppwn
          mv ~/work/iso/${{ matrix.architecture }}/alpine-pppwn-edge-${{ matrix.architecture }}.iso ~/work/iso/${{ matrix.architecture }}/pppwn-live-${{ matrix.architecture }}.iso

      # Upload ISO artifact for architecture
      - name: Upload ISO Artifact for ${{ matrix.architecture }}
        uses: actions/upload-artifact@v4
        with:
          name: pppwn-live-${{ matrix.architecture }}-iso
          path: |
            ~/work/iso/${{ matrix.architecture }}/*.iso