name: Build the pppwn_live ISO images

on:
  push:
    branches:
      - main
      - LLA
    paths:
      - '.github/workflows/ci.yaml'
      - 'custom/**'

permissions:
  contents: write
  discussions: write

jobs:
  build_iso:
    name: Build and Cross-Compile ISO Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Alpine Linux for ${{ matrix.architecture }}
        uses: jirutka/setup-alpine@v1
        with:
          arch: ${{ matrix.architecture }}
          branch: edge
          packages: |
            alpine-sdk
            alpine-conf
            xorriso
            squashfs-tools
            grub
            grub-efi
            doas
            alpine-base
            busybox
            openrc
            bash
            agetty
            wget
            mtools
            dosfstools
          shell-name: alpine

      - name: Prepare PPPwn binaries
        shell: alpine --root {0}
        env:
          ARCH: ${{ matrix.architecture }}
        run: |
          echo "ARCH is $ARCH"
          mkdir -p /tmp/pppwnlive
          cd /tmp/pppwnlive
          wget https://github.com/xfangfang/PPPwn_cpp/releases/latest/download/${ARCH}-linux-musl.zip
          unzip -p ${ARCH}-linux-musl.zip | tar -xzOf - pppwn > pppwn && rm ${ARCH}-linux-musl.zip
          wget https://github.com/B-Dem/PPPwnUI/raw/main/PPPwn/goldhen/1100/stage1.bin
          wget https://github.com/B-Dem/PPPwnUI/raw/main/PPPwn/goldhen/1100/stage2.bin
          cd /tmp
          tar -czf pppwn.tar.gz pppwnlive/*

      - name: Install required packages
        shell: alpine --root {0}
        env:
          ARCH: ${{ matrix.architecture }}
        run: |
          find /tmp -name "pppwn.tar.gz" -exec cp {} aports/scripts/pppwn.tar.gz \;
          echo "permit nopass root" | tee -a /etc/doas.conf
          abuild-keygen -i -a -n -q
          apk update
          mkdir -p ~/tmp ~/work/iso/${ARCH}
          export TMPDIR=~/tmp
          cp -rf custom/* aports/scripts/
          chmod +x aports/scripts/*
          ln -s /usr/lib/libalpine.sh /lib/libalpine.sh

      - name: Build ISO
        shell: alpine --root {0}
        env:
          ARCH: ${{ matrix.architecture }}
        run: |
          echo "Building ISO for ${ARCH}..."
          sh aports/scripts/mkimage.sh --tag stable --outdir ~/work/iso/${ARCH} --arch ${ARCH} --repository https://dl-cdn.alpinelinux.org/alpine/latest-stable/main --profile pppwn
          mv ~/work/iso/${ARCH}/alpine-pppwn-stable-${ARCH}.iso ~/work/iso/${ARCH}/pppwn-live-${ARCH}.iso

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: pppwn-live-${{ matrix.architecture }}-iso
          path: |
            ~/work/iso/${{ matrix.architecture }}/*.iso

  create_release:
    needs: build_iso
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: iso_images

      - name: Calculate SHA256 hashes
        id: sha256
        run: |
          SHA256_X86=$(sha256sum ./iso_images/pppwn-live-x86_64-iso/pppwn-live-x86_64.iso | awk '{print $1}')
          SHA256_AARCH64=$(sha256sum ./iso_images/pppwn-live-aarch64-iso/pppwn-live-aarch64.iso | awk '{print $1}')
          echo "sha256_x86=$SHA256_X86" >> $GITHUB_OUTPUT
          echo "sha256_aarch64=$SHA256_AARCH64" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |

            Changelog:
              ${{ github.event.head_commit.message }}

            SHA256 Checksums:
              - x86_64: `${{ steps.sha256.outputs.sha256_x86 }}`
              - aarch64: `${{ steps.sha256.outputs.sha256_aarch64 }}`
          files: |
            ./iso_images/pppwn-live-x86_64-iso/pppwn-live-x86_64.iso
            ./iso_images/pppwn-live-aarch64-iso/pppwn-live-aarch64.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
