name: Build Custom Alpine ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: Setup Alpine Linux environment
        uses: jirutka/setup-alpine@v1
        with:
          branch: edge
    
      - name: Install required packages and build ISO
        shell: alpine.sh --root {0}
        run: |
          apk add --no-cache alpine-sdk alpine-conf syslinux xorriso squashfs-tools grub grub-efi doas alpine-base busybox openrc bash agetty
          echo "permit nopass root" | tee -a /etc/doas.conf
          abuild-keygen -i -a -n -q
          apk update
          mkdir -p ~/tmp ~/iso
          export TMPDIR=~/tmp
          cp -rf custom/* aports/scripts/
          cp ./custom/pppwn.tar.gz aports/scripts/
          chmod +x aports/scripts/*
          sh aports/scripts/mkimage.sh --tag edge --outdir ~/iso --arch x86_64 --repository https://dl-cdn.alpinelinux.org/alpine/edge/main --profile pppwn

      - name: Copy ISO to shared location
        shell: alpine.sh --root {0}
        run: |
          cp ~/iso/*.iso /home/runner/iso/
      
      - name: Check if ISO was copied and exists
        run: |
          if [ -z "$(ls -A /home/runner/iso/*.iso 2>/dev/null)" ]; then
            echo "ISO not found. Exiting."
            exit 1
          fi

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: pppwn-live-iso
          path: ~/iso/*.iso