name: Build Custom Alpine ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
    
      - name: Setup Alpine Linux environment
        uses: jirutka/setup-alpine@v1
        with:
          branch: edge  # Use the edge branch for latest packages
    
      - name: Install required packages and build ISO
        shell: alpine.sh --root {0}
        run: |
          apk add alpine-sdk alpine-conf syslinux xorriso squashfs-tools grub grub-efi doas alpine-base busybox openrc bash agetty
          echo "permit nopass root" | tee -a /etc/doas.conf
          abuild-keygen -i -a -n -q
          apk update
          mkdir -pv ~/tmp && export TMPDIR=~/tmp
          cp -r custom/* aports/scripts/
          ls -la /home/runner/work/pppwn_live/pppwn_live
          cp /home/runner/work/aports/custom/pppwn.tar.gz aports/scripts/
          chmod +x aports/scripts/*.sh
          sh aports/scripts/mkimage.sh --tag edge --outdir ~/iso --arch x86_64 --repository https://dl-cdn.alpinelinux.org/alpine/edge/main --profile pppwn
    
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: pppwn-live-iso
          path: ~/iso/*.iso